#!/usr/bin/env bash
set -euo pipefail

INSTALLER=""
INSTALL_ROOT="/opt/AMD/Vitis/2025.2"
SKIP_APT=0

usage() {
  cat <<'EOF'
Usage:
  ./scripts/wsl_vitis_quick_setup.sh [--installer /path/to/FPGAs_AdaptiveSoCs_Unified_*.tar.gz] [--install-root /opt/AMD/Vitis/2025.2] [--skip-apt]

What this does:
1) Installs common Linux dependencies needed by Vitis installers/tools.
2) Optionally extracts a Vitis installer tarball and launches xsetup.
3) Creates ~/.vitis_aie_env.sh and appends it to ~/.bashrc when settings64.sh is found.
4) Prints tool checks for vitis, v++, aiecompiler, xchesscc.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --installer)
      INSTALLER="${2:-}"
      shift 2
      ;;
    --install-root)
      INSTALL_ROOT="${2:-}"
      shift 2
      ;;
    --skip-apt)
      SKIP_APT=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

echo "[wsl-vitis] user=$(whoami)"
echo "[wsl-vitis] distro=$(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '"')"

after_install_env() {
  local settings
  settings=""

  if [[ -f "$INSTALL_ROOT/Vitis/settings64.sh" ]]; then
    settings="$INSTALL_ROOT/Vitis/settings64.sh"
  else
    while IFS= read -r f; do
      settings="$f"
      break
    done < <(find /opt /tools "$HOME" -maxdepth 6 -type f -name settings64.sh 2>/dev/null || true)
  fi

  if [[ -n "$settings" ]]; then
    cat > "$HOME/.vitis_aie_env.sh" <<EOF
# Auto-generated by scripts/wsl_vitis_quick_setup.sh
source "$settings"
export PLATFORM_REPO_PATHS="\${XILINX_VITIS}/base_platforms"
EOF

    if ! grep -q "\.vitis_aie_env.sh" "$HOME/.bashrc"; then
      echo "source \"$HOME/.vitis_aie_env.sh\"" >> "$HOME/.bashrc"
    fi

    # shellcheck disable=SC1090
    source "$HOME/.vitis_aie_env.sh" || true
    echo "[wsl-vitis] environment hook written to $HOME/.vitis_aie_env.sh"
  else
    echo "[wsl-vitis] settings64.sh not found yet. Run this script again after installation."
  fi
}

if [[ "$SKIP_APT" -eq 0 ]]; then
  echo "[wsl-vitis] installing dependencies via apt (sudo required)..."
  sudo apt-get update -o Acquire::ForceIPv4=true || echo "[wsl-vitis] WARNING: apt update failed (no network?), proceeding with cached lists"
  # Ubuntu 24.04: libncurses5/libtinfo5 renamed to libncurses6/libtinfo6
  sudo apt-get install -y \
    build-essential \
    cpio \
    file \
    git \
    libglib2.0-0t64 \
    libncurses6 \
    libpython3-dev \
    libtinfo6 \
    rsync \
    unzip \
    xz-utils || echo "[wsl-vitis] WARNING: some apt packages failed, continuing anyway"
fi

if [[ -n "$INSTALLER" ]]; then
  if [[ ! -f "$INSTALLER" ]]; then
    echo "[wsl-vitis] installer not found: $INSTALLER" >&2
    exit 2
  fi

  workdir="$HOME/vitis_installer"
  rm -rf "$workdir"
  mkdir -p "$workdir"

  echo "[wsl-vitis] extracting installer..."
  case "$INSTALLER" in
    *.tar.gz|*.tgz) tar -xzf "$INSTALLER" -C "$workdir" ;;
    *.tar)          tar -xf  "$INSTALLER" -C "$workdir" ;;
    *)              tar -xf  "$INSTALLER" -C "$workdir" ;;
  esac

  xsetup_path=""
  while IFS= read -r f; do
    xsetup_path="$f"
    break
  done < <(find "$workdir" -type f -name xsetup -o -name xsetup.bin 2>/dev/null)

  if [[ -z "$xsetup_path" ]]; then
    echo "[wsl-vitis] xsetup not found after extraction." >&2
    exit 2
  fi

  chmod +x "$xsetup_path" || true

  echo "[wsl-vitis] launching interactive installer..."
  echo "[wsl-vitis] target install root suggestion: $INSTALL_ROOT"
  sudo "$xsetup_path"
fi

after_install_env

echo "[wsl-vitis] tool check:"
for t in vitis v++ aiecompiler xchesscc; do
  if command -v "$t" >/dev/null 2>&1; then
    echo "FOUND $t: $(command -v "$t")"
  else
    echo "MISSING $t"
  fi
done

echo "[wsl-vitis] done. If license is not configured, set XILINXD_LICENSE_FILE or LM_LICENSE_FILE."
